### PR TITLE
Travis CI + test environment

### LINKED ISSUE #6: Setting up tests
I'd like to set up some tests, but vim-vader doesn't seem to work (maybe it can't handle buffer mappings, I don't know). I'd try with Vspec, but I couldn't figure out how to set it up (needed programs/installation steps and such). If somebody has experience with it, some hint would be appreciated, thanks.

### PR DESCRIPTION
**Pull request by antoinemadec**
The test env is now mature enough, Travis CI is also working!
I double check that your commits fixed the issues I previously opened.
We can close #6 now I think.

In ```.travis.yml``` you will see that we are using ```vim 8.0.1529```
I chose this version randomly, please consider setting it up the the lowest version that is supposed to be compatible with your plugin.

You now have to create a travis account, sync it with your github and that should work right away.
If you want to add the badge reporting the build status, add something like this in your README.md (for master branch):
[Build Status](https://travis-ci.org/mg979/vim-visual-multi)

Also, we will have to populate the tests with more directories, and maybe give them names that make more sense than 'example1' :smile: 

As a side note, the convention for development branches is to call them ```dev```  rather than ```test```.
At first it confused me, I thought your ```test``` branch was a branch to work on the test environment.
But that's just me being nitpicky :confounded: 

I hope this helps!

Cheers,
Antoine

### CODE REVIEW

**Comment by mg979** [comment]
If you want to make it easy, checkout test (clean), take your test directory and commit.

**Comment by antoinemadec** [comment]
Oh, I thought I merged from my ```master``` to your ```test```.
Will try again.

**Comment by antoinemadec** [comment]
And voila 😄

**Comment by mg979** [comment]
Could you please do something like:
```
git checkout test (my test branch)
git checkout -b vrun (create a temporary branch from test branch)
git merge master --squash (your master with the tests)
```

so that everything is in one squashed commit, then make a PR with that branch? I could do it myself but then I'd be the author of the commit.

**Pull request closed without merging**
