### PR TITLE
remove annoying confirmation when exiting multi-cursor

### PR DESCRIPTION
**Pull request by zetatez**

### CODE REVIEW

**Comment by mg979** [comment]
That option (`g:VM_silent_exit`) must be set to 1 to have what you want.

**Comment by zetatez** [comment]
Thanks, but it still doesn't seem to work as expected, still prompts 'Press ENTER or type command to continue` when leaving multi-cursor.

**Comment by mg979** [comment]
By chance you use some nvim package manager? If so, learn to use it, there are similar issues in the tracker. The option works, there's no reason it shouldn't.

**Comment by mg979** [comment]
Also, if you really can't make it work, you can just make your changes and use your fork, there's no problem with that.

**Comment by zetatez** [comment]
I use neovim lazy plugin manager. I've tried this option. For sure, it can disable `Exited Visual-Multi.`, but can not disable `Press Enter or type command ...`. I tend to use my fork. Thanks.

**Pull request closed without merging**
