### PR TITLE
Make some mappings buffer-only

### PR DESCRIPTION
**Pull request by ashfinal**
Make `Visual Subtract/Reduce` and `Erase Regions` buffer mappings

### CODE REVIEW

**Comment by mg979** [comment]
Thanks but:
1. it's intentional that all visual mappings share the same leader, it's called visual for a reason and it would be confusing in any other way, otherwise you would have a 'visual leader' but visual mappings that use another leader. No.
2. the `Erase regions` plug will dropped soon

**Comment by ashfinal** [comment]
Never mind. I thought `g:VM_leader`'s visual leader was only for global mappings before entering VM mode. And I just checked, `Visual Subtract/Reduce` weren't mapped like `Visual Regex` or `Visual All`, they only gotta mapped after entering VM mode. But they all share similar name?

`Visual Regex` can be accessed from vim's common visual mode globally, `Visual Subtract/Reduce` can only be accessed after entering VM mode and in visual mode simultaneously, they appear to be buffer-only mappings to me.

**Comment by mg979** [comment]
`Visual Subtract/Reduce` are buffer mappings, but also `visual` mappings, that is they are started from visual mode, and this matters the most.

**Comment by ashfinal** [comment]
OK, that also sounds reasonable to me. But I don't like it interventing with
global mappings, with `z` as prefix it will give me clear message I'm interacting with region/pattern in VM mode.

**Comment by mg979** [comment]
You can remap them.

**Comment by ashfinal** [comment]
Yeah, remapping is a solution for me. Thanks anyway for the awesome plugin :)

**Pull request closed without merging**
